"""Host configuration from ``$VERDI_HOME/config.toml``.

Example (offline GPU host behind a jump box)::

    [paths]                      # big data on the bucket, small files local
    weights = "/mnt/bucket/verdi/weights"
    weights_no_rename = true     # bucket allows create/overwrite only:
                                 # download to local staging, then copy
    # hf_cache / runs may be overridden too (they need rename + delete)

    [network]
    pypi_index = "https://mirrors.aliyun.com/pypi/simple/"
    hf_endpoint = "https://hf-mirror.com"
    uv_python_downloads = "never"            # interpreters copied manually
    github_proxy = "https://gh-proxy.com/"   # prefix for github URLs, or
    github_mirror = "/opt/verdi/git-mirror"   # local mirror built by
                                             # `verdi offline-fetch`

    [build]                      # used by manifests as {cuda_home}/{cuda_arch}
    cuda_home = "/opt/verdi/cuda-12.8"
    cuda_arch = "12.0"
"""
from __future__ import annotations

import os
from functools import lru_cache
from typing import Any, Dict

GITHUB_HOSTS = ("https://github.com/", "https://raw.githubusercontent.com/",
                "https://codeload.github.com/")


@lru_cache(maxsize=None)
def load(home: str) -> Dict[str, Any]:
    from pathlib import Path

    from verdi.core.manifest import tomllib

    path = Path(home) / "config.toml"
    if not path.exists():
        return {}
    with open(path, "rb") as f:
        return tomllib.load(f)


def network(home: str) -> Dict[str, str]:
    return dict(load(home).get("network", {}))


def network_env(home: str) -> Dict[str, str]:
    """Env vars routing uv / huggingface_hub / git through mirrors."""
    net = network(home)
    env: Dict[str, str] = {}
    if net.get("pypi_index"):
        env["UV_DEFAULT_INDEX"] = net["pypi_index"]
        env["PIP_INDEX_URL"] = net["pypi_index"]
    if net.get("uv_python_downloads"):  # "never" on offline hosts
        env["UV_PYTHON_DOWNLOADS"] = net["uv_python_downloads"]
    if net.get("hf_endpoint"):
        env["HF_ENDPOINT"] = net["hf_endpoint"]
        # Xet-backed files redirect to cdn hosts mirrors do not proxy
        if net.get("hf_disable_xet", True):
            env["HF_HUB_DISABLE_XET"] = "1"
    if net.get("github_mirror"):
        # one insteadOf per host dir in the mirror (github.com, gitlab.com..)
        mirror = net["github_mirror"].rstrip("/")
        hosts = ["github.com"]
        if os.path.isdir(mirror):
            hosts += sorted(h for h in os.listdir(mirror)
                            if h != "github.com" and "." in h
                            and os.path.isdir(os.path.join(mirror, h)))
        kv = [(f"url.file://{mirror}/{h}/.insteadOf", f"https://{h}/")
              for h in hosts]
        # submodules rewritten to file:// are refused by default
        kv.append(("protocol.file.allow", "always"))
        env["GIT_CONFIG_COUNT"] = str(len(kv))
        for i, (k, v) in enumerate(kv):
            env[f"GIT_CONFIG_KEY_{i}"] = k
            env[f"GIT_CONFIG_VALUE_{i}"] = v
        # git drops GIT_CONFIG_* for nested submodules: also provide a
        # global config file (which includes the user's own ~/.gitconfig)
        env["GIT_CONFIG_GLOBAL"] = _mirror_gitconfig(home, mirror, hosts)
    elif net.get("github_proxy"):
        proxy = net["github_proxy"].rstrip("/") + "/"
        env["GIT_CONFIG_COUNT"] = "1"
        env["GIT_CONFIG_KEY_0"] = f"url.{proxy}https://github.com/.insteadOf"
        env["GIT_CONFIG_VALUE_0"] = "https://github.com/"
    return env


def _mirror_gitconfig(home: str, mirror: str, hosts) -> str:
    lines = ["# generated by verdi (core/config.py); do not edit",
             "[include]", f"\tpath = {os.path.expanduser('~/.gitconfig')}",
             '[protocol "file"]', "\tallow = always"]
    for h in hosts:
        lines += [f'[url "file://{mirror}/{h}/"]', f"\tinsteadOf = https://{h}/"]
    text = "\n".join(lines) + "\n"
    path = os.path.join(home, "gitconfig.mirror")
    try:
        old = open(path).read() if os.path.exists(path) else None
        if old != text:
            os.makedirs(home, exist_ok=True)
            with open(path, "w") as f:
                f.write(text)
    except OSError:
        pass
    return path


def paths_cfg(home: str) -> Dict[str, str]:
    return dict(load(home).get("paths", {}))


def build_cfg(home: str) -> Dict[str, str]:
    return dict(load(home).get("build", {}))


def rewrite_url(url: str, home: str) -> str:
    """Prefix GitHub download URLs with the configured proxy."""
    proxy = network(home).get("github_proxy")
    if proxy and url.startswith(GITHUB_HOSTS):
        return proxy.rstrip("/") + "/" + url
    return url
